FROM debian:8

RUN apt-get -y update && apt-get -y install locales
RUN locale-gen --no-purge en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8
RUN update-locale
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:fuzzgun/pybitmessage
RUN apt-get -y update
RUN apt-get -y upgrade

RUN apt-get install pybitmessage

ENV bm_api_host 0.0.0.0
ENV bm_api_port 8442
ENV bm_api_username bm-user
ENV bm_api_password placeholder

RUN echo "daemon = true\n"+\
    "apienabled = true\n"+\
    "apiinterface = $bm_api_host\n"+\
    "apiport = $bm_api_port\n"+\
    "apiusername = $bm_api_username\n"+\
    "apipassword = $bm_api_password\n"\
    >>  ~/.config/PyBitmessage/keys.dat

EXPOSE $bm_api_port
EXPOSE 8444

CMD []

ENTRYPOINT ["pybitmessage"]
